services:
  beat81:
    build: .
    env_file:
        - .env
    image: saeidimohsen/beat81:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - TZ=Europe/Berlin
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
